//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionnaireExample.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnketaEntities : DbContext
    {
        public AnketaEntities()
            : base("name=AnketaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<QE_Questions> QE_Questions { get; set; }
        public virtual DbSet<QE_QuestionsUserValue> QE_QuestionsUserValue { get; set; }
        public virtual DbSet<QE_User> QE_User { get; set; }
    }
}
