//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionnaireExample.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class QE_QuestionsUserValue
    {
        public int QE_ID { get; set; }
        public Nullable<int> QE_QUSERID { get; set; }
        public Nullable<int> QE_QID { get; set; }
        public int QE_VALUE { get; set; }
    
        public virtual QE_Questions QE_Questions { get; set; }
        public virtual QE_User QE_User { get; set; }
    }
}
