//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionnaireExample.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class QE_User
    {
        public QE_User()
        {
            this.QE_QuestionsUserValue = new HashSet<QE_QuestionsUserValue>();
        }
    
        public int QUSER_ID { get; set; }
        public string QUSER_NAME { get; set; }
    
        public virtual ICollection<QE_QuestionsUserValue> QE_QuestionsUserValue { get; set; }
    }
}
